[2024-04-15T23:33:13.354+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:33:13.669+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-15T23:33:14.095+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-15T23:33:14.114+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-15T23:33:14.392+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_python> on 2024-04-07 00:00:00+00:00
[2024-04-15T23:33:14.502+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:33:14.510+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2024-04-15T23:33:14.514+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecut7', 'ejecutar_script_python', 'scheduled__2024-04-07T00:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/Prueba.py', '--cfg-path', '/tmp/tmpwr8oovcc']
[2024-04-15T23:33:14.550+0000] {standard_task_runner.py:91} INFO - Job 221: Subtask ejecutar_script_python
[2024-04-15T23:33:15.517+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-07T00:00:00+00:00 [running]> on host b67ce4676396
[2024-04-15T23:33:17.527+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecut7' AIRFLOW_CTX_TASK_ID='ejecutar_script_python' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-07T00:00:00+00:00'
[2024-04-15T23:33:17.536+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:33:17.738+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:33:17.827+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:33:17.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:33:18.180+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecut7, task_id=ejecutar_script_python, execution_date=20240407T000000, start_date=20240415T233313, end_date=20240415T233318
[2024-04-15T23:33:18.434+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:33:18.727+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:33:18.864+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
