[2024-04-15T23:55:38.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:55:38.712+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T23:55:38.753+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T23:55:38.764+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T23:55:38.930+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_> on 2024-04-14 00:00:00+00:00
[2024-04-15T23:55:39.073+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=405) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:55:39.082+0000] {standard_task_runner.py:63} INFO - Started process 407 to run task
[2024-04-15T23:55:39.100+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecutaa', 'ejecutar_script_', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/holaa.py', '--cfg-path', '/tmp/tmprdnx3da_']
[2024-04-15T23:55:39.114+0000] {standard_task_runner.py:91} INFO - Job 254: Subtask ejecutar_script_
[2024-04-15T23:55:40.071+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-14T00:00:00+00:00 [running]> on host b67ce4676396
[2024-04-15T23:55:41.244+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecutaa' AIRFLOW_CTX_TASK_ID='ejecutar_script_' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T23:55:41.282+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:55:41.329+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/***/script.py'
[2024-04-15T23:55:41.330+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:55:41.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:55:41.368+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecutaa, task_id=ejecutar_script_, execution_date=20240414T000000, start_date=20240415T235538, end_date=20240415T235541
[2024-04-15T23:55:41.553+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:55:41.687+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:55:41.966+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
