[2024-04-15T23:33:21.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:33:21.959+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-15T23:33:22.297+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-08T00:00:00+00:00 [queued]>
[2024-04-15T23:33:22.331+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-15T23:33:22.829+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_python> on 2024-04-08 00:00:00+00:00
[2024-04-15T23:33:23.027+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecut7', 'ejecutar_script_python', 'scheduled__2024-04-08T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/Prueba.py', '--cfg-path', '/tmp/tmpzsabzuoz']
[2024-04-15T23:33:23.249+0000] {standard_task_runner.py:91} INFO - Job 226: Subtask ejecutar_script_python
[2024-04-15T23:33:22.941+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:33:23.747+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2024-04-15T23:33:25.117+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecut7.ejecutar_script_python scheduled__2024-04-08T00:00:00+00:00 [running]> on host b67ce4676396
[2024-04-15T23:33:26.238+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecut7' AIRFLOW_CTX_TASK_ID='ejecutar_script_python' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:00:00+00:00'
[2024-04-15T23:33:26.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:33:26.532+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/Prueba2.py'
[2024-04-15T23:33:26.534+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:33:26.540+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:33:26.651+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecut7, task_id=ejecutar_script_python, execution_date=20240408T000000, start_date=20240415T233322, end_date=20240415T233326
[2024-04-15T23:33:26.818+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:33:27.494+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:33:27.757+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
