[2024-04-15T23:56:15.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:56:15.166+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ manual__2024-04-15T23:55:57.928052+00:00 [queued]>
[2024-04-15T23:56:15.230+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ manual__2024-04-15T23:55:57.928052+00:00 [queued]>
[2024-04-15T23:56:15.235+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T23:56:15.328+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_> on 2024-04-15 23:55:57.928052+00:00
[2024-04-15T23:56:15.346+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=418) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:56:15.355+0000] {standard_task_runner.py:63} INFO - Started process 419 to run task
[2024-04-15T23:56:15.350+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecutaa', 'ejecutar_script_', 'manual__2024-04-15T23:55:57.928052+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/holaa.py', '--cfg-path', '/tmp/tmp3230jr6d']
[2024-04-15T23:56:15.360+0000] {standard_task_runner.py:91} INFO - Job 258: Subtask ejecutar_script_
[2024-04-15T23:56:15.458+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecutaa.ejecutar_script_ manual__2024-04-15T23:55:57.928052+00:00 [running]> on host b67ce4676396
[2024-04-15T23:56:15.732+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecutaa' AIRFLOW_CTX_TASK_ID='ejecutar_script_' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T23:55:57.928052+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T23:55:57.928052+00:00'
[2024-04-15T23:56:15.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:56:15.784+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/***/script.py'
[2024-04-15T23:56:15.787+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:56:15.796+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:56:15.828+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecutaa, task_id=ejecutar_script_, execution_date=20240415T235557, start_date=20240415T235615, end_date=20240415T235615
[2024-04-15T23:56:15.896+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:56:15.948+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:56:15.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
