[2024-04-23T18:18:31.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T18:18:31.461+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:18:14.946028+00:00 [queued]>
[2024-04-23T18:18:31.523+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:18:14.946028+00:00 [queued]>
[2024-04-23T18:18:31.527+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T18:18:31.621+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): tarea_mi_funcion> on 2024-04-23 18:18:14.946028+00:00
[2024-04-23T18:18:31.648+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nombre_del_dag', 'tarea_mi_funcion', 'manual__2024-04-23T18:18:14.946028+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/P3.py', '--cfg-path', '/tmp/tmplak2g8ji']
[2024-04-23T18:18:31.646+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T18:18:31.653+0000] {standard_task_runner.py:91} INFO - Job 398: Subtask tarea_mi_funcion
[2024-04-23T18:18:31.664+0000] {standard_task_runner.py:63} INFO - Started process 326 to run task
[2024-04-23T18:18:31.956+0000] {task_command.py:426} INFO - Running <TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:18:14.946028+00:00 [running]> on host 26fbc25bb53c
[2024-04-23T18:18:32.605+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tu_nombre' AIRFLOW_CTX_DAG_ID='nombre_del_dag' AIRFLOW_CTX_TASK_ID='tarea_mi_funcion' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T18:18:14.946028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T18:18:14.946028+00:00'
[2024-04-23T18:18:32.613+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T18:18:39.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T18:18:39.048+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Script.py", line 84, in ETL
    conn = psycopg2.connect(
           ^^^^^^^^
NameError: name 'psycopg2' is not defined
[2024-04-23T18:18:39.128+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=nombre_del_dag, task_id=tarea_mi_funcion, execution_date=20240423T181814, start_date=20240423T181831, end_date=20240423T181839
[2024-04-23T18:18:39.180+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 398 for task tarea_mi_funcion (name 'psycopg2' is not defined; 326)
[2024-04-23T18:18:39.243+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T18:18:39.275+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T18:18:39.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
