[2024-04-15T23:55:57.185+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T23:56:01.271+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-10T00:00:00+00:00 [queued]>
[2024-04-15T23:56:01.364+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-10T00:00:00+00:00 [queued]>
[2024-04-15T23:56:01.371+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T23:56:06.811+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ejecutar_script_> on 2024-04-10 00:00:00+00:00
[2024-04-15T23:56:07.228+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T23:56:07.234+0000] {standard_task_runner.py:63} INFO - Started process 410 to run task
[2024-04-15T23:56:07.233+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'm_dag_ejecutaa', 'ejecutar_script_', 'scheduled__2024-04-10T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/holaa.py', '--cfg-path', '/tmp/tmpkev7xwrv']
[2024-04-15T23:56:07.239+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask ejecutar_script_
[2024-04-15T23:56:09.399+0000] {task_command.py:426} INFO - Running <TaskInstance: m_dag_ejecutaa.ejecutar_script_ scheduled__2024-04-10T00:00:00+00:00 [running]> on host b67ce4676396
[2024-04-15T23:56:11.702+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='usuario' AIRFLOW_CTX_DAG_ID='m_dag_ejecutaa' AIRFLOW_CTX_TASK_ID='ejecutar_script_' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-10T00:00:00+00:00'
[2024-04-15T23:56:11.710+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T23:56:13.075+0000] {logging_mixin.py:188} INFO - Error al ejecutar el script: [Errno 2] No such file or directory: '/opt/***/script.py'
[2024-04-15T23:56:13.096+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-15T23:56:13.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T23:56:13.181+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=m_dag_ejecutaa, task_id=ejecutar_script_, execution_date=20240410T000000, start_date=20240415T235601, end_date=20240415T235613
[2024-04-15T23:56:13.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T23:56:13.953+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:56:13.962+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
