[2024-04-23T18:34:27.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T18:34:27.875+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:34:12.211975+00:00 [queued]>
[2024-04-23T18:34:27.911+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:34:12.211975+00:00 [queued]>
[2024-04-23T18:34:27.922+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T18:34:28.064+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): tarea_mi_funcion> on 2024-04-23 18:34:12.211975+00:00
[2024-04-23T18:34:28.131+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=501) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T18:34:28.139+0000] {standard_task_runner.py:63} INFO - Started process 503 to run task
[2024-04-23T18:34:28.122+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nombre_del_dag', 'tarea_mi_funcion', 'manual__2024-04-23T18:34:12.211975+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/P3.py', '--cfg-path', '/tmp/tmpbmzyhlom']
[2024-04-23T18:34:28.154+0000] {standard_task_runner.py:91} INFO - Job 403: Subtask tarea_mi_funcion
[2024-04-23T18:34:28.382+0000] {task_command.py:426} INFO - Running <TaskInstance: nombre_del_dag.tarea_mi_funcion manual__2024-04-23T18:34:12.211975+00:00 [running]> on host 26fbc25bb53c
[2024-04-23T18:34:32.408+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tu_nombre' AIRFLOW_CTX_DAG_ID='nombre_del_dag' AIRFLOW_CTX_TASK_ID='tarea_mi_funcion' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T18:34:12.211975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T18:34:12.211975+00:00'
[2024-04-23T18:34:32.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T18:35:20.207+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T18:35:20.212+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T18:35:20.241+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=nombre_del_dag, task_id=tarea_mi_funcion, execution_date=20240423T183412, start_date=20240423T183427, end_date=20240423T183520
[2024-04-23T18:35:25.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T18:35:25.246+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T18:35:36.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
